spring:
  application:
    name: zuul   
  cloud:
    config:
      override-none: true
    #我们可以设置禁止配置中心的配置将客户端配置覆盖掉
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true
  #开启重试

#sensitive-headers:
#zuul 会过滤敏感 http 协议头，默认过滤以下协议头：
#Cookie
#Set-Cookie
#Authorization
#可以设置 zuul 不过滤这些协议头

#  routes:
#拦截路径
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
    
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
#此设置一般应大于 ribbon 的重试超时时长，例如 10 秒

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
